"""Initial

Revision ID: fddbebe2de11
Revises: 
Create Date: 2024-11-05 15:29:18.152563

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fddbebe2de11"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "EXECUTION_STATISTICS",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_name", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("start_date_time", sa.TIMESTAMP(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("warehouse_size", sa.String(length=20), nullable=True),
        sa.Column("number_of_campaigns", sa.Integer(), nullable=True),
        sa.Column("number_of_customers", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        """
        INSERT INTO EXECUTION_STATISTICS (tenant_name, task_id, start_date_time, duration, warehouse_size, number_of_campaigns, number_of_customers)
        VALUES 
            ('ULVEGR', 'validate_schema', '2024-08-20 11:38:46.702', 1.055586, 'X-Small', 31, 22320370),
            ('ULVEGR', 'count_plan_ids_to_execute', '2024-08-20 11:38:51.490', 1.010017, 'X-Small', 31, 22320370),
            ('ULVEGR', 'prepare_stream_constraint', '2024-08-20 11:39:07.889', 432.14872, 'X-Small', 31, 22320370);
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("EXECUTION_STATISTICS")
    # ### end Alembic commands ###
